"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from datetime import timedelta
from dotenv import load_dotenv
from celery.schedules import crontab
import cloudinary
import cloudinary.uploader
import cloudinary.api
from decimal import Decimal

# Load .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-if8j+=!jy#771sta3@19&m-xyu)p6#*4zb@kh$v0u-jt35(a6x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ["ALLOWED_HOSTS"].split(",")

# Cloudinary Configuration
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
    api_key=os.environ.get('CLOUDINARY_API_KEY'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
    secure=True
)

# Payment Gateway Settings
PAYMENT_GATEWAYS = {
    'paystack': {
        'public_key': os.environ.get('PAYSTACK_PUBLIC_KEY', ''),
        'secret_key': os.environ.get('PAYSTACK_SECRET_KEY', ''),
        'base_url': 'https://api.paystack.co',
        'webhook_secret': os.environ.get('PAYSTACK_WEBHOOK_SECRET', ''),
        'split_code': os.environ.get('PAYSTACK_SPLIT_CODE', None),
    },
    'flutterwave': {
        'public_key': os.environ.get('FLUTTERWAVE_PUBLIC_KEY', ''),
        'secret_key': os.environ.get('FLUTTERWAVE_SECRET_KEY', ''),
        'base_url': 'https://api.flutterwave.com/v3',
        'webhook_secret': os.environ.get('FLUTTERWAVE_WEBHOOK_SECRET', ''),
        'encryption_key': os.environ.get('FLUTTERWAVE_ENCRYPTION_KEY', ''),
    }
}

# Payment configuration
PAYMENT_SETTINGS = {
    'MAX_PAYMENT_ATTEMPTS_PER_HOUR': 5,
    'PAYMENT_EXPIRY_MINUTES': 30,
    'MIN_COURSE_PRICE': Decimal('500.00'),  # 500 NGN minimum
    'MAX_COURSE_PRICE': Decimal('500000.00'),  # 500k NGN maximum
    'AUTO_REFUND_THRESHOLD': Decimal('50000.00'),  # Auto-process refunds below 50k
    'INSTRUCTOR_REVENUE_SHARE': Decimal('0.70'),  # 70% to instructor
    'PLATFORM_REVENUE_SHARE': Decimal('0.30'),  # 30% to platform
}

# Optional: YouTube API key for better duration extraction
YOUTUBE_API_KEY = os.environ.get('YOUTUBE_API_KEY')

# Video processing settings
VIDEO_PROCESSING = {
    'MAX_FILE_SIZE_GB': 1,  # 1GB max per video
    'SUPPORTED_FORMATS': ['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'],
    'AUTO_GENERATE_THUMBNAILS': True,
    'EXTRACT_DURATION': True,
}

# Nigerian Bank Codes (for reference)
NIGERIAN_BANK_CODES = {
    'ACCESS_BANK': '044',
    'CITIBANK': '023',
    'DIAMOND_BANK': '063',
    'ECOBANK': '050',
    'FIDELITY_BANK': '070',
    'FIRST_BANK': '011',
    'FIRST_CITY_MONUMENT_BANK': '214',
    'GUARANTY_TRUST_BANK': '058',
    'HERITAGE_BANK': '030',
    'KEYSTONE_BANK': '082',
    'POLARIS_BANK': '076',
    'PROVIDUS_BANK': '101',
    'STANBIC_IBTC': '221',
    'STANDARD_CHARTERED': '068',
    'STERLING_BANK': '232',
    'UNION_BANK': '032',
    'UNITED_BANK_FOR_AFRICA': '033',
    'UNITY_BANK': '215',
    'WEMA_BANK': '035',
    'ZENITH_BANK': '057',
}

# Payment Settings
DEFAULT_CURRENCY = 'NGN'
SUPPORTED_CURRENCIES = ['NGN', 'USD', 'GHS', 'KES']
DEFAULT_PAYMENT_GATEWAY = 'paystack'
SITE_URL = os.environ.get('SITE_URL', 'https://yourdomain.com')

# Course Creator Settings
ALLOW_USER_COURSE_CREATION = True
COURSE_APPROVAL_REQUIRED = True  # Set to False if you want auto-approval
INSTRUCTOR_REVENUE_SHARE = 70  # Percentage that goes to instructor (70%)
PLATFORM_REVENUE_SHARE = 30   # Percentage that goes to platform (30%)

# Email Settings for Course Management
COURSE_NOTIFICATION_EMAILS = {
    'NEW_COURSE_SUBMISSION': True,
    'COURSE_APPROVED': True,
    'COURSE_REJECTED': True,
    'NEW_ENROLLMENT': True,
    'COURSE_COMPLETED': True,
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'django_celery_beat',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Your apps
    'users',
    'courses',
    'progress',
    'chats',
    'payments',
    'adminpanel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'common.debug_middleware.DebugUserMiddleware',
    'common.middleware.SessionValidationMiddleware',
    'common.middleware.RateLimitMiddleware', 
    'common.middleware.SecurityHeadersMiddleware',  
    'common.middleware.RequestLoggingMiddleware',
    'common.middleware.UserActivityMiddleware', 
    'common.middleware.SuspiciousActivityMiddleware', 
    'common.course_middleware.PaymentSecurityMiddleware',
    'common.middleware.ErrorHandlingMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# JWT Settings
JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY')
JWT_ACCESS_TOKEN_LIFETIME = 60  # minutes
JWT_REFRESH_TOKEN_LIFETIME = 7   # days

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT'))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

# Frontend URL (for email links)
FRONTEND_URL = os.environ.get('FRONTEND_URL')

"""
# Database Settings for MongoDB (using djongo)
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': os.environ.get('DB_NAME'),
        'CLIENT': {
            'host': os.environ.get('DB_HOST'),
            'username': os.environ.get('DB_USER'),
            'password': os.environ.get('DB_PASSWORD'),
            'authSource': os.environ.get('DB_AUTH_SOURCE', 'admin'),
            'authMechanism': 'SCRAM-SHA-1',
        }
    }
}
"""

# Database Settings for PostgreSQL
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Cache Settings (for rate limiting)
if os.environ.get("REDIS_URL"):
    # Use Redis if environment variable is set
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get("REDIS_URL"),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                # Optional: password, SSL, parser class, etc.
            }
        }
    }
    print("✅ Using Redis cache:", os.environ.get("REDIS_URL"))
else:
    # Fallback to built-in in-memory cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique',
        }
    }
    print("⚠️ Using in-memory cache (Redis not configured)")


# GeoIP2 Settings (for location detection)
GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')

# Session Settings
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# Security Settings
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT').lower() == 'true'
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# CORS Settings (if using django-cors-headers)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS').split(',')

CORS_ALLOW_CREDENTIALS = True

# REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'common.authentication.JWTAuthentication',
        # Optionally keep session auth for admin panel:
        # 'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.IsAuthenticated',
        # We'll use custom permissions instead of IsAuthenticated
        'rest_framework.permissions.AllowAny',  # Let middleware handle auth
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# Rate Limiting Settings
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

# Celery Settings (for background tasks)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')
CELERY_TIMEZONE = 'UTC'

CELERY_TASK_ROUTES = {
    'management.tasks.cleanup_old_records': {'queue': 'cleanup'},
    'management.tasks.cleanup_expired_tokens': {'queue': 'cleanup'},
    'management.tasks.process_scheduled_deletions': {'queue': 'high_priority'},
    'management.tasks.send_deletion_reminders': {'queue': 'emails'},
    'management.tasks.database_health_check': {'queue': 'monitoring'},
}

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    # Run monthly payout calculation on 1st of every month at 2 AM
    'create-monthly-payouts': {
        'task': 'payments.tasks.create_monthly_payouts_task',
        'schedule': crontab(hour=2, minute=0, day_of_month=1),
    },
    # Auto-process small payouts daily at 10 AM
    'auto-process-payouts': {
        'task': 'payments.tasks.process_auto_payouts',
        'schedule': crontab(hour=10, minute=0),
        'kwargs': {'max_amount': 10000}  # Auto-process up to 10k NGN
    },
    'cleanup-old-records': {
        'task': 'management.tasks.cleanup_old_records',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
    },
    'cleanup-expired-tokens': {
        'task': 'management.tasks.cleanup_expired_tokens',
        'schedule': crontab(minute=0, hour='*/6'),  # Run every 6 hours
    },
    'process-scheduled-deletions': {
        'task': 'management.tasks.process_scheduled_deletions',
        'schedule': crontab(hour=3, minute=0),  # Run daily at 3 AM
    },
    'cleanup-inactive-sessions': {
        'task': 'management.tasks.cleanup_inactive_sessions',
        'schedule': crontab(minute=0, hour='*/12'),  # Run every 12 hours
    },
    'cleanup-old-login-attempts': {
        'task': 'management.tasks.cleanup_old_login_attempts',
        'schedule': crontab(hour=4, minute=0, day_of_week=0),  # Run weekly on Sunday
    },
    'cleanup-old-email-logs': {
        'task': 'management.tasks.cleanup_old_email_logs',
        'schedule': crontab(hour=5, minute=0, day_of_month=1),  # Run monthly
    },
    'send-deletion-reminders': {
        'task': 'management.tasks.send_deletion_reminders',
        'schedule': crontab(hour=10, minute=0),  # Run daily at 10 AM
    },
    'database-health-check': {
        'task': 'management.tasks.database_health_check',
        'schedule': crontab(hour=1, minute=0),  # Run daily at 1 AM
    },
}



# Logging Configuration
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG_DIR = os.path.join(BASE_DIR, 'log')

if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 1024*512,  # 512 KB
            'backupCount': 2,      # Only 2 backups
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['file', 'console'],  # Send logs to file and console
        'level': 'INFO',
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Media files configuration for Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET')
}

# Use Cloudinary for media storage
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Video upload limits
MAX_VIDEO_SIZE = 500 * 1024 * 1024  # 500MB
ALLOWED_VIDEO_FORMATS = ['mp4', 'mov', 'avi', 'mkv']

# Course limits per user
MAX_COURSES_PER_INSTRUCTOR = 50  # Set to None for unlimited
FREE_COURSES_LIMIT = 5  # How many free courses an instructor can create

# Media URL and Root (Cloudinary handles this)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
